DROP TABLE assinaturas.DOC_ASSINATURA;

CREATE TABLE assinaturas.DOC_ASSINATURA
(
  CD_DOC_ASSINATURA               INTEGER NOT NULL,
  CD_TIP_DOC_ASSINATURA           INTEGER NOT NULL,
  CD_ATENDIMENTO                  INTEGER,
  CD_PACIENTE                     INTEGER,
  CD_PRESTADOR                    INTEGER,
  DT_DOC_ASSINATURA               DATE,
  DS_DOC_ASSINATURA               VARCHAR(100) NOT NULL,
  ANEXO_DOC_ASSINATURA            BLOB NOT NULL,
  CD_USUARIO_CADASTRO             VARCHAR(100) NOT NULL,
  CD_PRESTADOR_CADASTRO           INTEGER NULL,
  HR_CADASTRO                     TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO     VARCHAR(100) NOT NULL,
  CD_PRESTADOR_ULTIMA_ALTERACAO   INTEGER NULL,
  HR_ULTIMA_ALTERACAO             TIMESTAMP  
);

DROP SEQUENCE assinaturas.SEQ_CD_DOC_ASSINATURA;

CREATE SEQUENCE assinaturas.SEQ_CD_DOC_ASSINATURA
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE
ORDER;

COMMENT ON COLUMN DOC_ASSINATURA.CD_DOC_ASSINATURA 
IS 'SEQ_CD_DOC_ASSINATURA';
