DROP TABLE assinaturas.TIP_DOC_ASSINATURA;

CREATE TABLE assinaturas.TIP_DOC_ASSINATURA
(
  CD_TIP_DOC_ASSINATURA           INTEGER NOT NULL,
  DS_TIP_DOC_ASSINATURA           VARCHAR(100) NOT NULL,
  SN_ATIVO                        VARCHAR(1) NOT NULL,
  CD_USUARIO_CADASTRO             VARCHAR(100) NOT NULL,
  HR_CADASTRO                     TIMESTAMP NOT NULL,
  CD_USUARIO_ULTIMA_ALTERACAO     VARCHAR(100) NOT NULL,
  HR_ULTIMA_ALTERACAO             TIMESTAMP  
);

DROP SEQUENCE assinaturas.SEQ_CD_TIP_DOC_ASSINATURA;

CREATE SEQUENCE assinaturas.SEQ_CD_TIP_DOC_ASSINATURA
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE
ORDER;

COMMENT ON COLUMN TIP_DOC_ASSINATURA.CD_TIP_DOC_ASSINATURA 
IS 'SEQ_CD_TIP_DOC_ASSINATURA';

ALTER TABLE assinaturas.TIP_DOC_ASSINATURA
ADD CONSTRAINT CK_TIP_DOC_SN_ATIVO
CHECK (SN_ATIVO IN ('S','N'));

COMMENT ON COLUMN TIP_DOC_ASSINATURA.SN_ATIVO 
IS 'S - SIM / N - NAO';
